// services/pdf.service.ts
import PDFDocument from "pdfkit";
import fs from "fs";
import path from "path";
//import { Document } from "interfaces"; // define interface for record if you want

/**
 * generateMedicalPDF
 * - record: the mongo document or plain object with fields to print
 * - returns: local file path of generated PDF
 */
export async function generateMedicalPDF(record: any): Promise<string> {
  return new Promise((resolve, reject) => {
    try {
      const outDir = path.resolve(process.cwd(), "tmp_pdf");
      if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });

      const fileName = `medical_record_${record._id || Date.now()}.pdf`;
      const filePath = path.join(outDir, fileName);

      const doc = new PDFDocument({ size: "A4", margin: 40 });
      const stream = fs.createWriteStream(filePath);
      doc.pipe(stream);

      // Header
      doc.fontSize(18).text("PHIẾU HỒ SƠ BỆNH ÁN", { align: "center" });
      doc.moveDown(0.5);

      // Meta
      doc.fontSize(11);
      doc.text(`Record ID: ${record._id || record.recordId || "N/A"}`);
      doc.text(`Patient: ${record.patientName || record.patientId || "N/A"}`);
      doc.text(`Doctor: ${record.doctorName || record.doctorId || "N/A"}`);
      doc.text(`Visit date: ${new Date(record.visitDate || record.createdAt || Date.now()).toLocaleString()}`);
      doc.moveDown();

      // Sections
      const pushSection = (title: string, content: string) => {
        doc.fontSize(12).fillColor("#333").text(title, { continued: false, underline: true });
        doc.moveDown(0.2);
        doc.fontSize(10).fillColor("#000").text(content || "—", { align: "left" });
        doc.moveDown(0.6);
      };

      pushSection("Triệu chứng (Symptoms)", record.symptoms || "");
      pushSection("Khám thực thể (Physical exam)", record.physicalExam || "");
      pushSection("Chẩn đoán (Diagnosis)", record.diagnosis || "");
      pushSection("Điều trị (Treatment)", record.treatment || "");

      // Attachments thumbnails (if small images provided)
      if (record.attachments && Array.isArray(record.attachments) && record.attachments.length) {
        doc.addPage();
        doc.fontSize(14).text("Tệp đính kèm", { align: "left" });
        doc.moveDown(0.5);
        for (let i = 0; i < record.attachments.length && i < 6; i++) {
          try {
            const url = record.attachments[i];
            // if it's a local path -> drawImage; else skip (PDFKit can't draw remote)
            if (fs.existsSync(url)) {
              const x = 40 + (i % 2) * 260;
              const y = doc.y;
              doc.image(url, x, y, { fit: [220, 220], align: "center", valign: "center" });
              if (i % 2 === 1) doc.moveDown(12);
            } else {
              // print URL text
              doc.fontSize(9).text(`Attachment ${i + 1}: ${url}`);
            }
          } catch (err) {
            // ignore single attachment error
            continue;
          }
        }
      }

      // Footer
      doc.addPage();
      doc.fontSize(10).text("Generated by Clinic System", { align: "center" });

      doc.end();
      stream.on("finish", () => resolve(filePath));
      stream.on("error", (e) => reject(e));
    } catch (err) {
      reject(err);
    }
  });
}
