/// Flutter data model for an Invoice (Hóa đơn thanh toán).
///
/// Maps to the [Invoices] MongoDB collection defined in the ERD.
///
/// ERD Relationships:
/// - Invoices --[generates_1]--> MedicalRecords (via [recordId])
/// - Invoices --[processed_by]--> Cashier role
/// - Invoices --[online_payment]--> PaymentGateway (VNPay, Momo)
///
/// Blockchain Anchor:
/// The [transactionHash] stores the Ethereum Tx Hash confirming payment
/// was recorded on-chain. Maps to `transactionHash: String (Blockchain Anchor)`.
library;

/// Possible payment statuses for an invoice.
/// Defined as `Enum(Pending, Paid)` in the ERD.
enum InvoiceStatus {
  /// Invoice has been generated but payment not yet received.
  pending,

  /// Payment has been successfully received and confirmed.
  paid;

  /// Converts a raw API string to [InvoiceStatus].
  static InvoiceStatus fromString(String? value) {
    switch (value?.toLowerCase()) {
      case 'paid':
        return InvoiceStatus.paid;
      case 'pending':
      default:
        return InvoiceStatus.pending;
    }
  }

  /// Raw string value stored in the database.
  String get value => this == InvoiceStatus.paid ? 'Paid' : 'Pending';

  /// Vietnamese display label for UI.
  String get displayName =>
      this == InvoiceStatus.paid ? 'Đã thanh toán' : 'Chờ thanh toán';
}

/// The canonical Flutter model for an Invoice document.
///
/// Generated by the system when a [MedicalRecord] is finalized.
/// The [Cashier] processes payment and updates [status] to [InvoiceStatus.paid].
/// Optional online payments go through [PaymentGateway] (VNPay, Momo).
class Invoice {
  // ── Identity ───────────────────────────────────────────────────────────────

  /// MongoDB ObjectId string. Maps to `_id`.
  final String id;

  /// Reference to the [MedicalRecord] this invoice was generated from.
  /// Maps to `recordId`.
  final String recordId;

  // ── Financial Data ─────────────────────────────────────────────────────────

  /// Total amount due in VND. Maps to `totalAmount: Double`.
  final double totalAmount;

  /// Payment method used (e.g., "Tiền mặt", "VNPay", "Momo", "Thẻ ngân hàng").
  /// Maps to `paymentMethod: String`.
  final String? paymentMethod;

  /// Current payment status. Maps to `status: Enum(Pending, Paid)`.
  final InvoiceStatus status;

  // ── Blockchain Anchor ──────────────────────────────────────────────────────

  /// Ethereum transaction hash confirming on-chain payment record.
  ///
  /// After a payment is processed by [PaymentGateway], the transaction
  /// details are hashed and anchored via Smart Contract. This field stores
  /// the resulting Tx Hash for auditability.
  /// Maps to `transactionHash: String (Blockchain Anchor)` in the ERD.
  final String? transactionHash;

  // ── Display / Metadata ─────────────────────────────────────────────────────

  /// Optional patient name for list display (denormalized).
  final String? patientName;

  /// Optional doctor name for display.
  final String? doctorName;

  /// Timestamp when this invoice was created.
  final DateTime? createdAt;

  /// Timestamp when payment was confirmed.
  final DateTime? paidAt;

  /// Creates an [Invoice].
  const Invoice({
    required this.id,
    required this.recordId,
    required this.totalAmount,
    required this.status,
    this.paymentMethod,
    this.transactionHash,
    this.patientName,
    this.doctorName,
    this.createdAt,
    this.paidAt,
  });

  /// Deserializes an [Invoice] from a backend API JSON payload.
  factory Invoice.fromJson(Map<String, dynamic> json) {
    return Invoice(
      id: json['_id']?.toString() ?? '',
      recordId: json['recordId']?.toString() ?? '',
      totalAmount: (json['totalAmount'] as num?)?.toDouble() ?? 0.0,
      paymentMethod: json['paymentMethod']?.toString(),
      status: InvoiceStatus.fromString(json['status']?.toString()),
      transactionHash: json['transactionHash']?.toString(),
      patientName: json['patientName']?.toString(),
      doctorName: json['doctorName']?.toString(),
      createdAt: json['createdAt'] != null
          ? DateTime.tryParse(json['createdAt'].toString())
          : null,
      paidAt: json['paidAt'] != null
          ? DateTime.tryParse(json['paidAt'].toString())
          : null,
    );
  }

  /// Serializes this [Invoice] to a JSON map for API submission.
  Map<String, dynamic> toJson() => {
        'recordId': recordId,
        'totalAmount': totalAmount,
        if (paymentMethod != null) 'paymentMethod': paymentMethod,
        'status': status.value,
      };

  /// Formatted total amount as Vietnamese currency string.
  /// Example: "1.500.000 VNĐ"
  String get formattedAmount {
    final formatted = totalAmount
        .toInt()
        .toString()
        .replaceAllMapped(
          RegExp(r'(\d{1,3})(?=(\d{3})+(?!\d))'),
          (m) => '${m[1]}.',
        );
    return '$formatted VNĐ';
  }

  /// Returns true if this invoice has an on-chain payment record.
  bool get isOnChainAnchored =>
      transactionHash != null && transactionHash!.isNotEmpty;

  /// Creates a copy with optionally updated fields.
  Invoice copyWith({
    String? id,
    String? recordId,
    double? totalAmount,
    String? paymentMethod,
    InvoiceStatus? status,
    String? transactionHash,
    String? patientName,
    String? doctorName,
    DateTime? createdAt,
    DateTime? paidAt,
  }) {
    return Invoice(
      id: id ?? this.id,
      recordId: recordId ?? this.recordId,
      totalAmount: totalAmount ?? this.totalAmount,
      paymentMethod: paymentMethod ?? this.paymentMethod,
      status: status ?? this.status,
      transactionHash: transactionHash ?? this.transactionHash,
      patientName: patientName ?? this.patientName,
      doctorName: doctorName ?? this.doctorName,
      createdAt: createdAt ?? this.createdAt,
      paidAt: paidAt ?? this.paidAt,
    );
  }
}
